app/__init__.py
# from flask_uploads import UploadSet, configure_uploads,IMAGES
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
# from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail
from flask_login import LoginManager
# from flask_simplemde import SimpleMDE



bootstrap = Bootstrap()
db = SQLAlchemy()
mail = Mail()
# photos = UploadSet('photos',IMAGES)
# simple = SimpleMDE()



login_manager = LoginManager()
login_manager.session_protection = 'strong' #provides different security levels.
login_manager.login_view = 'auth.login'


def create_app(config_name):

    # inititalizing application
    app = Flask(__name__)
    

 
    # creating the app configurations
    app.config.from_object(config_options[config_name])

    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)
    # simple.init_app(app)


    #registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/auth')

   

    # configure UploadSet
    # configure_uploads(app,photos)
    
    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views, errors

app/main/views.py
from flask import render_template,request,redirect,url_for,abort
from . import main
from .forms import PitchForm,CommentForm, UpdateProfile
from ..models import User,Pitch,Comments
from flask_login import login_required,current_user
# from .. import db,photos
# import markdown2  

@main.route('/')
def index():

    '''
    View root page function that returns the index page and its data
    '''

    all_pitches=Pitch.query.order_by('id').all()
    # print(all_pitches)
    title='Pitches App'
    return render_template('index.html' , all_pitches=all_pitches, title=title)
@main.route('/pitch/newpitch', methods=['POST', 'GET'])
@login_required
def new_pitch():
    form = PitchForm()
    if form.validate_on_submit():
        title = form.title.data
        category = form.category.data
        newPitch = form.pitch_info.data
        #update pitch instance
        new_pitch = Pitch(pitch_title=title,pitch_category=category,pitch_itself=newPitch,user=current_user)

        
        #save pitch
        new_pitch.save_pitch()
        return redirect(url_for('.index'))
    title = 'Add New pitch'
    return render_template('pitches.html', title=title, pitchesform=form)
@main.route('/category/sports')
def sports():
    '''
    view function to display sports pitches
    '''
    pitches=Pitch.get_pitches('sports')
    sports_title ='sports Pitches'
    return render_template('pitches/sports.html',title=sports_title,sports_pitch=pitches)
@main.route('/category/business')
def business():
    '''
    view function to display business pitches
    '''
    pitches=Pitch.get_pitches('business')
    business_title='Business Pitches'
    return render_template('pitches/business.html',title=business_title, business_pitch=pitches)

@main.route('/category/politics')
def politics():
    '''
    view function to display business pitches
    '''
    pitches=Pitch.get_pitches('politics')
    politics_title = 'Politics Pitches'
    return render_template('pitches/politics.html',title=politics_title,politics_pitch=pitches)

@main.route('/comment/<int:id>', methods=['POST', 'GET'])
@login_required
def post_comment(id):
    pitche = Pitch.getPitchId(id)
    comments = Comments.get_comments(id)
    if request.args.get("like"):
        pitch = Pitch.query.filter_by(user_id=current_user.id)
        pitch.likes += 1
        print(pitch.likes)
        db.session.add(pitch.likes)
        db.session.commit()
        return str(pitch.likes)
    elif request.args.get("dislike"):
        pitche.dislikes += 1
        db.session.add()
        db.session.commit()
        return redirect(".comment")
    form = CommentForm()
    if form.validate_on_submit():
        comment = form.comment.data
        new_comment = Comments(comment_itself=comment,
                               user_id=current_user.id,
                               pitches_id=pitche.id)
        new_comment.save_comment()
        return redirect(url_for('main.post_comment', id=pitche.id))
    return render_template('comment.html',
                           commentform=form,
                           comments=comments,
                           pitch=pitche)
@main.route('/pitch/upvote/<int:id>&<int:vote>')
@login_required
def vote(id, vote):
    counter = 0
    pitchethrill = Pitch.getPitchId(id)
    # vote = .get_vote(id)
    counter += 1
    print(counter)
    new_vote = Pitch(likes=counter)
    new_vote.save_vote()
    return str(new_vote)


@main.route('/user/<uname>')
@login_required
def profile(uname):
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user)


@main.route('/user/<uname>/update',methods = ['GET','POST'])
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname = user.username))

    return render_template('profile/update.html',form = form)

@main.route('/user/<uname>/update/pic',methods = ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile',uname = uname))

app/templates/comment.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf%}
{% import 'macros.html' as macro %}
{%block styles%}
{{super()}}
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
    integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
<link rel="stylesheet" href="{{url_for('static',filename='css/bootstrap.min.css')}}"/>
<script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
{%endblock%}
{%block content%}
<h3 class="text-center text-uppercase" style="color:#cf3a15;font-family: 'Open Sans', sans-serif;">Comments</h3>
<div class="container">
    <hr>
    <div class="row">
        <div class="col-md-6">
            {{macro.displayPitches(pitchethrills)}}
            <h3 class="pt-3"><b>{{pitch.pitch_title}}</b></h3>
            <hr>
            <p>{{pitch.pitch_comment}}</p>
            <p><b>Posted on: </b>{{pitch.posted.strftime('%d.%m.%Y')}}</p>

            <i id="like" class="fa fa-thumbs-up" aria-hidden="true"></i>
            <span id='noOfLikes'></span>
            <i id="dislike" class="fa fa-thumbs-down" aria-hidden="true"></i>
            <span id='noOfDislikes'></span>
        </div>
        <div class="col-md-6">
            {{ wtf.quick_form(commentform) }}
            <h3>Display comments</h3>
            {{macro.displayComments(comments)}}
        </div>
    </div>
</div>
</div>
<script>
    $(document).ready(function(){
        var like=0
        var dislike=0
        $("#like").click(function(){
            like++;
            document.getElementById("noOfLikes").innerHTML=like
    });
    $("#dislike").click(function(){
            dislike++;
            document.getElementById("noOfDislikes").innerHTML=dislike
    });   
    });
</script>
{% endblock %}

app/templates/macros.html
{% macro displayPitches(pitches_list) %}
    {% for pitch in pitches_list %}
    <div class="pitch-card">
        <div class="card col-sm mt-2">
            <div class="well well-lg p-5" style="text-align: left;">
                <h3 style="font-weight: 900;">{{pitch.pitch_title}}</h3>
                <p>{{pitch.pitch_itself}}</p>
                <p>{{pitch.pitch_comment|truncate(70)}}</p>
                <p style="font-weight: 900; "><span>Posted on: {{pitch.posted.strftime('%d.%m.%Y')}} by :
                </span> {{pitch.user.username}} <span>
                    </span>
                </p>
                <div class="row">
                    <div class="btn-group col-md-8">
                     <br>
                    </div>
                    <div class=col-md-6>
                        <a href="{{url_for('main.post_comment',id=pitch.id)}}" class="btn btn-default btn-center -center">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                class="bi bi-pen-fill" viewBox="0 0 16 16">
                                <path
                                    d="m13.498.795.149-.149a1.207 1.207 0 1 1 1.707 1.708l-.149.148a1.5 1.5 0 0 1-.059 2.059L4.854 14.854a.5.5 0 0 1-.233.131l-4 1a.5.5 0 0 1-.606-.606l1-4a.5.5 0 0 1 .131-.232l9.642-9.642a.5.5 0 0 0-.642.056L6.854 4.854a.5.5 0 1 1-.708-.708L9.44.854A1.5 1.5 0 0 1 11.5.796a1.5 1.5 0 0 1 1.998-.001z" />
                            </svg>Comment</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    {%endmacro%}
    {%macro displayComments(comments_list)%}
    {%for comment in comments_list%}
    <div class="col-md-12">
        <p>{{comment.comment_itself}}</p>
        <h5>By : {{comment.user.username}}</h5>
    </div>
    {%endfor%}
    {%endmacro%}

app/templates/navbar.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <div class="navbar navbar-inverse" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">pitch</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="/">Home</a></li>
                </ul>
           

                <ul class="nav navbar-nav navbar-right">
                 
                  {% if current_user.is_authenticated %}
                  <li><a href="#">{{current_user.username}}</a></li>
                  <li><a href="{{url_for('main.profile',uname = current_user.username)}}">Profile</a></li>
                  <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
                  {% else %}
                  <li><a href="#">Guest</a></li>
                  <li><a href="{{url_for('auth.login')}}">Sign in</a></li>
                  {%endif%}
                </ul>
            </div>

        </div>
    </div>
  </body>
</html>

app/templates/pitches.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf%}
{%block content%}
<div class="col-md-8 card mt-3 p-5">
    {{wtf.quick_form(pitchesform)}}
</div>
{% endblock %}

app/templates/pitches/business.html
{% extends 'base.html'%}
{% import 'macros.html' as macro %}
    {%block content%}
    <div class="container">
        <div class="card" style="width: 20rem;">
            <div class="card-body ">
            <h4 class="card-title" style="font-weight:900">{{title}}</h4>
                {{macro.displayPitches(business_pitch)}}
            </div>
        </div>
    </div>
    {%endblock%}

app/templates/pitches/politics.html
{% extends 'base.html'%}
{% import 'macros.html' as macro %}
    {%block content%}
    <div class="container">
        <div class="card" style="width: 20rem;">
            <div class="card-body ">
            <h4 class="card-title" style="font-weight:900">{{title}}</h4>
                {{macro.displayPitches(politics_pitch)}}
            </div>
        </div>
    </div>
    {%endblock%}

app/templates/pitches/sports.html
{% extends 'base.html'%}
{% import 'macros.html' as macro %}
    {%block content%}
    <div class="container">
        <div class="card" style="width: 20rem;">
            <div class="card-body ">
            <h4 class="card-title" style="font-weight:900">{{title}}</h4>
                {{macro.displayPitches(sports_pitch)}}
            </div>
        </div>
    </div>
    {%endblock%}

app/templates/profile/profile.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf%}

{% block content %}

<div class="container">

<div class="row">


  <div class="col-md-4">
    <h3> {{user.username| capitalize}} </h3>

    {% if user.bio %}
      <p> {{user.bio}}</p>

    {%else%}
      <p> {{user.username| capitalize}} has no bio </p>
    {% endif %}

    {% if user == current_user %}
      <a href="{{url_for('main.update_profile',uname = user.username)}}">Edit profile</a>
    {% endif %}

  </div>
  <div class="col-md-4">
    {% if user.profile_pic_path %}

    <img src="{{url_for('static',filename = user.profile_pic_path)}}" alt="" class="img-thumbnail">

    {%else%}

    <p>No profile picture</p>

    {% endif %}

    {% if user == current_user %}
    <form  action="{{url_for('main.update_pic',uname = user.username)}}" method="post" enctype = "multipart/form-data">

      <input type="file"  name="photo" class="form-control" required>
      <input class="btn btn-success btn-sm" type="submit">
    </form>
      {% endif %}
  </div>


</div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}